# Generated by Django 2.2 on 2019-04-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodCategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='cat_specialday',
            field=models.CharField(choices=[('monday_special', 'Monday Special'), ('cranchy_tuesday', 'Cranchy Tuesday'), ('weno_tamutamu', 'Weno TamuTamu')], default='Please Select First', max_length=120),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='cat_title',
            field=models.CharField(choices=[('breakfast', 'BreakFast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='Please Select First', max_length=120),
        ),
    ]
