# Generated by Django 2.2 on 2019-04-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodCategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_titile', models.CharField(max_length=120)),
                ('food_slug', models.SlugField(blank=True, unique=True)),
                ('food_description', models.TextField()),
                ('food_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodCategories.FoodCategory')),
            ],
        ),
    ]
